name: Vatensa
favicon: null
layout_spectrum: 0.866863653762266
typography_spectrum: 0.24347889539785683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1551010711118579
  lightness: 0.03352364548482001
  saturation: 0.6192558398470283
  rhythmicContrast: 0.5177548034116626
purpose: []
