name: Vatensa
favicon: null
layout_spectrum: 0.01412
typography_spectrum: 0.27589
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#89c4e7'
    - '#0076b7'
    - '#fcfcfc'
    - '#000000'
    - '#00ffff'
  brandStrength: 0.5
  lightness: 0.03352364548482001
  saturation: 0.6192558398470283
  rhythmicContrast: 0.5177548034116626
purpose: []
